name: ${project.name}
main: ${project.groupId}.${project.artifactId}
version: ${project.version}
description: ${project.description}
website: ${project.url}
author: Topeka_
api-version: 1.14
depend: [WorldEdit, AsyncWorldEdit]
commands:
  sheepwar:
    aliases: sw
    usage: /sw help
    description: SheepWar command
    permission: SheepWar.use
